### ISSUE TITLE
Individual vacation property listing pages

### ISSUE THREAD

**Issue by rmtwombly** [chingu-voyages/v30-bears-team-05#13]
**__Feature Description__**
Each property added to the site will be given a detailed listing page, and include price, calendar availability, and description. This is important so that users may be able to make informed decisions when reserving a property. 

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1: Family member views listing page
- [ ] User Story or Task #2: Vacationer views listing page
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
