### ISSUE TITLE
Google Sign-In

### ISSUE THREAD

**Issue by rmtwombly** [chingu-voyages/v30-bears-team-05#18]
**__Feature Description__**
This feature will allow users to create an account and use a secured sign-in to view their existing vacation reservations, listing details, contact and payment information. This feature is important for both the user and the admin/site owner as it will provide a secure way to keep track of users, property availability and account data. 

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1: User Sign-In
- [ ] User Story or Task #2: Admin Sign-In
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.

**Comment by rmtwombly** [comment]
video tutorials for MERN: 

[https://www.youtube.com/watch?v=8LDgiePQPTU](url)

[https://www.youtube.com/watch?v=_ABAIvf7SGQ](url)
