### ISSUE TITLE
Booking Process 

### ISSUE THREAD

**Issue by rmtwombly** [chingu-voyages/v30-bears-team-05#23]
**__Feature Description__**
This portion will be dedicated primarily to the functionality of the calendar, selecting booking dates, including property availability, selection for user including Check-in, Check-out Dates, Property Selection and Securing Reservation.

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1: User Booking
- [ ] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
